
version: 2.1
orbs:
  node: circleci/node@4.7.0

obs:
  test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build
      - run:
          command: yarn test
          name: Run tests
workflows:
  test_my_app:
    jobs:
      - test
